
package View;

import Controller.AtendimentoDAO;
import Model.Atendimento;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author guilherme
 */
public class AlterarAtendimento extends javax.swing.JFrame {
    private static int idAtendimento;
    private static int idAdmin;
    AtendimentoDAO ad;
    Atendimento a;
    TelaAdmin ta;
    /**
     * Creates new form AlterarAtendimento
     */
    public AlterarAtendimento(String idatendimento, int idAdmin) throws SQLException {
        initComponents();
        this.idAtendimento =  Integer.parseInt(idatendimento);
        this.idAdmin = idAdmin;
        try {
            this.populaDados(idAtendimento);
        } catch (SQLException ex) {
            Logger.getLogger(AlterarAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        encaminhar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        setor = new javax.swing.JLabel();
        horachamado = new javax.swing.JLabel();
        tipoEquipamento = new javax.swing.JLabel();
        urgencia = new javax.swing.JLabel();
        idEquipamento = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Encaminhamento de Atendimentos");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Tipo de equipamento");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Descrição do problema");

        descricao.setEditable(false);
        descricao.setColumns(20);
        descricao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 0, 0));
        descricao.setLineWrap(true);
        descricao.setRows(5);
        descricao.setToolTipText("");
        descricao.setCaretColor(new java.awt.Color(255, 0, 0));
        descricao.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        descricao.setEnabled(false);
        jScrollPane1.setViewportView(descricao);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setText("Tipo de urgência");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setText("Data solicitada");

        encaminhar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        encaminhar.setText("Fazer encaminhamento");
        encaminhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encaminharActionPerformed(evt);
            }
        });

        cancelar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        setor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        setor.setForeground(new java.awt.Color(255, 0, 0));
        setor.setText("Setor_Texto");
        setor.setFocusable(false);

        horachamado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        horachamado.setForeground(new java.awt.Color(255, 0, 0));
        horachamado.setText("Data_Texto");
        horachamado.setFocusable(false);

        tipoEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        tipoEquipamento.setForeground(new java.awt.Color(255, 0, 0));
        tipoEquipamento.setText("Tipo_Texto");
        tipoEquipamento.setFocusable(false);

        urgencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        urgencia.setForeground(new java.awt.Color(255, 0, 0));
        urgencia.setText("Urgência_Texto");
        urgencia.setFocusable(false);

        idEquipamento.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        idEquipamento.setForeground(new java.awt.Color(255, 0, 0));
        idEquipamento.setText("Id_Texto");
        idEquipamento.setFocusable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setText("Id do equipamento");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Setor Localizado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(187, 187, 187))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                        .addGap(334, 334, 334)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(encaminhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(setor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(horachamado, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(idEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(urgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tipoEquipamento))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idEquipamento)
                            .addComponent(jLabel8))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(urgencia))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setor)
                            .addComponent(jLabel6))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horachamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encaminhar)
                    .addComponent(cancelar))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encaminharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encaminharActionPerformed
        ad = new AtendimentoDAO();
        int i = ad.finalizarAtendimento(this.idAdmin, this.idAtendimento);
        this.dispose();
        try {
            ta = new TelaAdmin(this.idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(AlterarAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        ta.setVisible(true);
    }//GEN-LAST:event_encaminharActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
        try {
            ta = new TelaAdmin(this.idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(AlterarAtendimento.class.getName()).log(Level.SEVERE, null, ex);
        }
        ta.setVisible(true);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AlterarAtendimento((idAtendimento+""),idAdmin).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AlterarAtendimento.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton encaminhar;
    private javax.swing.JLabel horachamado;
    private javax.swing.JLabel idEquipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel setor;
    private javax.swing.JLabel tipoEquipamento;
    private javax.swing.JLabel urgencia;
    // End of variables declaration//GEN-END:variables
    public void populaDados(int idAtendimento) throws SQLException{
        ad = new AtendimentoDAO();
        a = new Atendimento();
        a = ad.buscaAtendimento(idAtendimento);
        this.tipoEquipamento.setText(a.getTipoEquipamento());
        this.idEquipamento.setText(a.getIdEquipamento());
        
        if (a.getUrgencia()==0) 
            this.urgencia.setText("Sem urgência");
        if (a.getUrgencia()==1) 
            this.urgencia.setText("Com urgência");
        
        this.setor.setText(a.getSetorAtendimento().getNome());
        this.horachamado.setText(a.getHoraChamado());
        this.descricao.setText(a.getDescricao());
    }
}
