
package View;

import Controller.AdminDAO;
import Controller.AtendimentoDAO;
import Model.Admin;
import Model.Atendimento;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

public class TelaAdmin extends javax.swing.JFrame {
    private static int idAdmin;
    AdminDAO ad;
    Admin a;
    AtendimentoDAO atd;
    AlterarAtendimento alterA;
    public TelaAdmin(int idAdmin) throws SQLException {
        initComponents();
        this.idAdmin = idAdmin;
        this.setDados(idAdmin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        cadastroCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        setor = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        tituloChamada = new javax.swing.JLabel();
        recarregarLista = new javax.swing.JToggleButton();
        chamadaEquipamento1 = new javax.swing.JLabel();
        finalizarSessao = new javax.swing.JButton();
        chamadaNome1 = new javax.swing.JLabel();
        chamadaEncaminhar1 = new javax.swing.JButton();
        chamadaEquipamento2 = new javax.swing.JLabel();
        chamadaNome2 = new javax.swing.JLabel();
        chamadaEncaminhar2 = new javax.swing.JButton();
        chamadaEquipamento3 = new javax.swing.JLabel();
        chamadaNome3 = new javax.swing.JLabel();
        chamadaEncaminhar3 = new javax.swing.JButton();
        chamadaEquipamento4 = new javax.swing.JLabel();
        chamadaNome4 = new javax.swing.JLabel();
        chamadaEncaminhar4 = new javax.swing.JButton();
        chamadaEquipamento5 = new javax.swing.JLabel();
        chamadaNome5 = new javax.swing.JLabel();
        chamadaEncaminhar5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        excluirCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        title.setText("Olá ");

        cadastroCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cadastroCliente.setText("Cadastrar Cliente");
        cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Seu nome: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Seu login: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Seu setor: ");

        nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nome.setText("Nome");

        setor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        setor.setText("Login");

        login.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        login.setText("Login");

        tituloChamada.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        tituloChamada.setText("Chamadas pendentes para seu setor");

        recarregarLista.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        recarregarLista.setText("Recarregar a lista");
        recarregarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recarregarListaActionPerformed(evt);
            }
        });

        chamadaEquipamento1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEquipamento1.setText("Equipamento");

        finalizarSessao.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        finalizarSessao.setText("Finalizar Sessão");
        finalizarSessao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarSessaoActionPerformed(evt);
            }
        });

        chamadaNome1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaNome1.setText("Hora");

        chamadaEncaminhar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEncaminhar1.setText("Encaminar");
        chamadaEncaminhar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamadaEncaminhar1ActionPerformed(evt);
            }
        });

        chamadaEquipamento2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEquipamento2.setText("Equipamento");

        chamadaNome2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaNome2.setText("Hora");

        chamadaEncaminhar2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEncaminhar2.setText("Encaminar");
        chamadaEncaminhar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamadaEncaminhar2ActionPerformed(evt);
            }
        });

        chamadaEquipamento3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEquipamento3.setText("Equipamento");

        chamadaNome3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaNome3.setText("Hora");

        chamadaEncaminhar3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEncaminhar3.setText("Encaminar");
        chamadaEncaminhar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamadaEncaminhar3ActionPerformed(evt);
            }
        });

        chamadaEquipamento4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEquipamento4.setText("Equipamento");

        chamadaNome4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaNome4.setText("Hora");

        chamadaEncaminhar4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEncaminhar4.setText("Encaminar");
        chamadaEncaminhar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamadaEncaminhar4ActionPerformed(evt);
            }
        });

        chamadaEquipamento5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEquipamento5.setText("Equipamento");

        chamadaNome5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaNome5.setText("Hora");

        chamadaEncaminhar5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chamadaEncaminhar5.setText("Encaminar");
        chamadaEncaminhar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamadaEncaminhar5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Seus dados");

        excluirCliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        excluirCliente.setText("Remover Cliente");
        excluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(setor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(nome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(finalizarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(excluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(recarregarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chamadaEquipamento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaEquipamento2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaEquipamento3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaEquipamento4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaEquipamento5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chamadaNome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaNome3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaNome4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaNome5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chamadaNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chamadaEncaminhar1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chamadaEncaminhar2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chamadaEncaminhar3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chamadaEncaminhar4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chamadaEncaminhar5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nome))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(setor)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(login))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cadastroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(excluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(finalizarSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(tituloChamada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(chamadaEncaminhar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(chamadaNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chamadaEncaminhar2)
                                    .addComponent(chamadaNome2)
                                    .addComponent(chamadaEquipamento2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chamadaEncaminhar3)
                                    .addComponent(chamadaNome3)
                                    .addComponent(chamadaEquipamento3))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chamadaNome4)
                                    .addComponent(chamadaEquipamento4)
                                    .addComponent(chamadaEncaminhar4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(chamadaEncaminhar5)
                                    .addComponent(chamadaNome5)
                                    .addComponent(chamadaEquipamento5)))
                            .addComponent(chamadaEquipamento1))
                        .addGap(29, 29, 29)
                        .addComponent(recarregarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroClienteActionPerformed
        CadastroCliente cc;
        cc= new CadastroCliente(this, true);
        this.dispose();
        cc.setVisible(true);
        
        this.setVisible(true);
    }//GEN-LAST:event_cadastroClienteActionPerformed

    private void finalizarSessaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarSessaoActionPerformed
        this.dispose();
        Principal p = new Principal();
        p.setVisible(true);
    }//GEN-LAST:event_finalizarSessaoActionPerformed

    private void recarregarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recarregarListaActionPerformed
        try {
            this.setDados(idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_recarregarListaActionPerformed

    private void chamadaEncaminhar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamadaEncaminhar4ActionPerformed
        this.dispose();
        try {
            alterA = new AlterarAtendimento(this.chamadaEncaminhar4.getToolTipText(), this.idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        alterA.setVisible(true);
    }//GEN-LAST:event_chamadaEncaminhar4ActionPerformed

    private void chamadaEncaminhar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamadaEncaminhar3ActionPerformed
        this.dispose();
        try {
            alterA = new AlterarAtendimento(this.chamadaEncaminhar3.getToolTipText(), this.idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        alterA.setVisible(true);
    }//GEN-LAST:event_chamadaEncaminhar3ActionPerformed

    private void chamadaEncaminhar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamadaEncaminhar2ActionPerformed
       this.dispose();
        try {
            alterA = new AlterarAtendimento(this.chamadaEncaminhar2.getToolTipText(), this.idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        alterA.setVisible(true);
    }//GEN-LAST:event_chamadaEncaminhar2ActionPerformed

    private void chamadaEncaminhar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamadaEncaminhar1ActionPerformed
        this.dispose();
        try {
            alterA = new AlterarAtendimento(this.chamadaEncaminhar1.getToolTipText(), this.idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        alterA.setVisible(true);
    }//GEN-LAST:event_chamadaEncaminhar1ActionPerformed

    private void chamadaEncaminhar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamadaEncaminhar5ActionPerformed
        this.dispose();
        try {
            alterA = new AlterarAtendimento(this.chamadaEncaminhar5.getToolTipText(), this.idAdmin);
        } catch (SQLException ex) {
            Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        alterA.setVisible(true);
    }//GEN-LAST:event_chamadaEncaminhar5ActionPerformed

    private void excluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClienteActionPerformed
        RemoverCliente rc;
        rc= new RemoverCliente(this, true);
        this.dispose();
        rc.setVisible(true);
        
        this.setVisible(true);        
    }//GEN-LAST:event_excluirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaAdmin(idAdmin).setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(TelaAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroCliente;
    private javax.swing.JButton chamadaEncaminhar1;
    private javax.swing.JButton chamadaEncaminhar2;
    private javax.swing.JButton chamadaEncaminhar3;
    private javax.swing.JButton chamadaEncaminhar4;
    private javax.swing.JButton chamadaEncaminhar5;
    private javax.swing.JLabel chamadaEquipamento1;
    private javax.swing.JLabel chamadaEquipamento2;
    private javax.swing.JLabel chamadaEquipamento3;
    private javax.swing.JLabel chamadaEquipamento4;
    private javax.swing.JLabel chamadaEquipamento5;
    private javax.swing.JLabel chamadaNome1;
    private javax.swing.JLabel chamadaNome2;
    private javax.swing.JLabel chamadaNome3;
    private javax.swing.JLabel chamadaNome4;
    private javax.swing.JLabel chamadaNome5;
    private javax.swing.JButton excluirCliente;
    private javax.swing.JButton finalizarSessao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel login;
    private javax.swing.JLabel nome;
    private javax.swing.JToggleButton recarregarLista;
    private javax.swing.JLabel setor;
    private javax.swing.JLabel title;
    private javax.swing.JLabel tituloChamada;
    // End of variables declaration//GEN-END:variables
    public void setDados(int id) throws SQLException{
        ad = new AdminDAO();
        a = ad.buscaAdmin(id);
        this.title.setText("Olá "+a.getNome());
        this.nome.setText(a.getNome());
        this.login.setText(a.getLogin());
        this.setor.setText(a.getSetor().getNome());
                
        atd = new AtendimentoDAO();
        ArrayList<Atendimento> lista = atd.atendimentoSetor(a.getSetor().getIdSetor());
        if(lista.size()>4){
            this.chamadaEquipamento1.setText(lista.get(0).getTipoEquipamento());this.chamadaNome1.setText(lista.get(0).getHoraChamado());this.chamadaEncaminhar1.setToolTipText( lista.get(0).getIdAtendimento() +"" );
            this.chamadaEquipamento2.setText(lista.get(1).getTipoEquipamento());this.chamadaNome2.setText(lista.get(1).getHoraChamado());this.chamadaEncaminhar2.setToolTipText( lista.get(1).getIdAtendimento() +"" );
            this.chamadaEquipamento3.setText(lista.get(2).getTipoEquipamento());this.chamadaNome3.setText(lista.get(2).getHoraChamado());this.chamadaEncaminhar3.setToolTipText( lista.get(2).getIdAtendimento() +"" );
            this.chamadaEquipamento4.setText(lista.get(3).getTipoEquipamento());this.chamadaNome4.setText(lista.get(3).getHoraChamado());this.chamadaEncaminhar4.setToolTipText( lista.get(3).getIdAtendimento() +"" );
            this.chamadaEquipamento5.setText(lista.get(4).getTipoEquipamento());this.chamadaNome5.setText(lista.get(4).getHoraChamado());this.chamadaEncaminhar5.setToolTipText( lista.get(4).getIdAtendimento() +"" );
        }else if(lista.size()==4){
            this.chamadaEquipamento1.setText(lista.get(0).getTipoEquipamento());this.chamadaNome1.setText(lista.get(0).getHoraChamado());this.chamadaEncaminhar1.setToolTipText( lista.get(0).getIdAtendimento() +"" );
            this.chamadaEquipamento2.setText(lista.get(1).getTipoEquipamento());this.chamadaNome2.setText(lista.get(1).getHoraChamado());this.chamadaEncaminhar2.setToolTipText( lista.get(1).getIdAtendimento() +"" );
            this.chamadaEquipamento3.setText(lista.get(2).getTipoEquipamento());this.chamadaNome3.setText(lista.get(2).getHoraChamado());this.chamadaEncaminhar3.setToolTipText( lista.get(2).getIdAtendimento() +"" );
            this.chamadaEquipamento4.setText(lista.get(3).getTipoEquipamento());this.chamadaNome4.setText(lista.get(3).getHoraChamado());this.chamadaEncaminhar4.setToolTipText( lista.get(3).getIdAtendimento() +"" );
            this.chamadaEquipamento5.setVisible(false);this.chamadaNome5.setVisible(false);this.chamadaEncaminhar5.setVisible(false);
        }else if(lista.size()==3){
            this.chamadaEquipamento1.setText(lista.get(0).getTipoEquipamento());this.chamadaNome1.setText(lista.get(0).getHoraChamado());this.chamadaEncaminhar1.setToolTipText( lista.get(0).getIdAtendimento() +"" );
            this.chamadaEquipamento2.setText(lista.get(1).getTipoEquipamento());this.chamadaNome2.setText(lista.get(1).getHoraChamado());this.chamadaEncaminhar2.setToolTipText( lista.get(1).getIdAtendimento() +"" );
            this.chamadaEquipamento3.setText(lista.get(2).getTipoEquipamento());this.chamadaNome3.setText(lista.get(2).getHoraChamado());this.chamadaEncaminhar3.setToolTipText( lista.get(2).getIdAtendimento() +"" );
            this.chamadaEquipamento4.setVisible(false);this.chamadaNome4.setVisible(false);this.chamadaEncaminhar4.setVisible(false);
            this.chamadaEquipamento5.setVisible(false);this.chamadaNome5.setVisible(false);this.chamadaEncaminhar5.setVisible(false);
        }else if(lista.size()==2){
            this.chamadaEquipamento1.setText(lista.get(0).getTipoEquipamento());this.chamadaNome1.setText(lista.get(0).getHoraChamado());this.chamadaEncaminhar1.setToolTipText( lista.get(0).getIdAtendimento() +"" );
            this.chamadaEquipamento2.setText(lista.get(1).getTipoEquipamento());this.chamadaNome2.setText(lista.get(1).getHoraChamado());this.chamadaEncaminhar2.setToolTipText( lista.get(1).getIdAtendimento() +"" );
            this.chamadaEquipamento3.setVisible(false);this.chamadaNome3.setVisible(false);this.chamadaEncaminhar3.setVisible(false);
            this.chamadaEquipamento4.setVisible(false);this.chamadaNome4.setVisible(false);this.chamadaEncaminhar4.setVisible(false);
            this.chamadaEquipamento5.setVisible(false);this.chamadaNome5.setVisible(false);this.chamadaEncaminhar5.setVisible(false);
        }else if(lista.size()==1){
            this.chamadaEquipamento1.setText(lista.get(0).getTipoEquipamento());this.chamadaNome1.setText(lista.get(0).getHoraChamado());this.chamadaEncaminhar1.setToolTipText( lista.get(0).getIdAtendimento() +"" );
            this.chamadaEquipamento2.setVisible(false);this.chamadaNome2.setVisible(false);this.chamadaEncaminhar2.setVisible(false);
            this.chamadaEquipamento3.setVisible(false);this.chamadaNome3.setVisible(false);this.chamadaEncaminhar3.setVisible(false);
            this.chamadaEquipamento4.setVisible(false);this.chamadaNome4.setVisible(false);this.chamadaEncaminhar4.setVisible(false);
            this.chamadaEquipamento5.setVisible(false);this.chamadaNome5.setVisible(false);this.chamadaEncaminhar5.setVisible(false);
        }if(lista.size()<1){
            this.chamadaEquipamento1.setVisible(false);this.chamadaNome1.setVisible(false);this.chamadaEncaminhar1.setVisible(false);
            this.chamadaEquipamento2.setVisible(false);this.chamadaNome2.setVisible(false);this.chamadaEncaminhar2.setVisible(false);
            this.chamadaEquipamento3.setVisible(false);this.chamadaNome3.setVisible(false);this.chamadaEncaminhar3.setVisible(false);
            this.chamadaEquipamento4.setVisible(false);this.chamadaNome4.setVisible(false);this.chamadaEncaminhar4.setVisible(false);
            this.chamadaEquipamento5.setVisible(false);this.chamadaNome5.setVisible(false);this.chamadaEncaminhar5.setVisible(false);
            this.tituloChamada.setText("Não há atendimentos abertos!");
        }
    }

}
